@api-version=v1.0
@api-url={{api_url}}/{{api-version}}
@health-url={{api-url}}/health
@workflows-url={{api-url}}/workflows


### Ping
GET {{health-url}}/ping

### Get all WFs
GET {{workflows-url}}

### Get WF details
GET {{workflows-url}}/1

### Register WF
POST {{workflows-url}}
Authorization: Bearer {{$auth.token("auth-id")}}

{
    "name": "dummy-wf",
    "description": "Dummy WF"
}
