"""Initial schema.

Revision ID: c0c07ddc40ed
Revises:
Create Date: 2026-01-22 10:32:38.758163

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c0c07ddc40ed"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalogues",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("item_type", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("keywords", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("language", sa.Text(), nullable=True),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("license", sa.Text(), nullable=True),
        sa.Column("conforms_to", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "contacts",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("organization", sa.Text(), nullable=True),
        sa.Column("roles", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.CheckConstraint("entity_type IN ('catalogue', 'record')", name="ck_contacts_entity_type"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_contacts_entity", "contacts", ["entity_id", "entity_type"], unique=False)
    op.create_table(
        "links",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("entity_id", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("href", sa.Text(), nullable=False),
        sa.Column("rel", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("jupyter_kernel", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint("entity_type IN ('catalogue', 'record', 'contact')", name="ck_links_entity_type"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_links_entity", "links", ["entity_id", "entity_type"], unique=False)
    op.create_table(
        "records",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("catalogue_id", sa.Text(), nullable=True),
        sa.Column("type", sa.Enum("workflow", "notebook", name="record_type"), nullable=False),
        sa.Column("geometry", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("conforms_to", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("keywords", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("language", sa.Text(), nullable=True),
        sa.Column("license", sa.Text(), nullable=True),
        sa.Column("applicable_collections", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("input_parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("application_type", sa.Text(), nullable=True),
        sa.Column("application_container", sa.Boolean(), nullable=True),
        sa.Column("application_language", sa.Text(), nullable=True),
        sa.Column("extent", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("jupyter_kernel_info", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("formats", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["catalogue_id"], ["catalogues.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_records_catalogue", "records", ["catalogue_id"], unique=False)
    op.create_index("idx_records_keywords", "records", ["keywords"], unique=False, postgresql_using="gin")
    op.create_index("idx_records_type", "records", ["type"], unique=False)
    op.create_table(
        "themes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("catalogue_id", sa.Text(), nullable=False),
        sa.Column("scheme", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["catalogue_id"], ["catalogues.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_themes_catalogue", "themes", ["catalogue_id"], unique=False)
    op.create_table(
        "concepts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("theme_id", sa.Integer(), nullable=False),
        sa.Column("concept_id", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["theme_id"], ["themes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("concepts")
    op.drop_index("idx_themes_catalogue", table_name="themes")
    op.drop_table("themes")
    op.drop_index("idx_records_type", table_name="records")
    op.drop_index("idx_records_keywords", table_name="records", postgresql_using="gin")
    op.drop_index("idx_records_catalogue", table_name="records")
    op.drop_table("records")
    op.drop_index("idx_links_entity", table_name="links")
    op.drop_table("links")
    op.drop_index("idx_contacts_entity", table_name="contacts")
    op.drop_table("contacts")
    op.drop_table("catalogues")
    # ### end Alembic commands ###
